# -*- coding: utf-8 -*-

EXECUTABLE_DIRECTOR_ACTIONS = {
    "CONTINUE",
    "AUTO_REGENERATE",
    "GO_BACK_TO_WORLDVIEW",
    "GO_BACK_TO_CHARACTERS",
    "GO_BACK_TO_SKELETON_EXPANSION",
    "WAIT_USER",
    "FINISH",
    "INCREMENTAL_MODIFY_CHARACTER",
    "INCREMENTAL_APPEND_CHARACTER",
    "INCREMENTAL_MODIFY_SKELETON",
    "INCREMENTAL_MODIFY_CHARACTER_FULL",
    "TOOL_CALL",
}
